#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This file is part of convertdate.
# http://github.com/fitnr/convertdate

# Licensed under the MIT license:
# http://opensource.org/licenses/MIT
# Copyright (c) 2016, fitnr <fitnr@fakeisthenewreal>
language: python

python:
 - 2.7
 - 3.3
 - 3.4
 - 3.5

# Use container-based infrastructure
sudo: false

script:
 - python setup.py test
